DROP TABLE IF EXISTS Student;

CREATE TABLE IF NOT EXISTS Student(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NULL,
    dob varchar(255) NULL,
    CONSTRAINT student_pkey PRIMARY KEY (id)
);
DELETE FROM Student;
INSERT INTO Student(name, dob) VALUES ('Phong', '25/08/2015');
INSERT INTO Student(name, dob) VALUES ('Phuc', '12/11/1992');